// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// ==/ClosureCompiler==

/*!
 * jQuery Form Plugin
 * version: 3.31.0-2013.03.27
 * @requires jQuery v1.5 or later
 *
 * Examples and documentation at: http://malsup.com/jquery/form/
 * Project repository: https://github.com/malsup/form
 * Dual licensed under the MIT and GPL licenses:
 *    http://malsup.github.com/mit-license.txt
 *    http://malsup.github.com/gpl-license-v2.txt
 */
(function(b){function u(a){var f=a.data;a.isDefaultPrevented()||(a.preventDefault(),b(this).ajaxSubmit(f))}function A(a){var f=a.target,c=b(f);if(!c.is("[type=submit],[type=image]")){f=c.closest("[type=submit]");if(0===f.length)return;f=f[0]}var d=this;d.clk=f;"image"==f.type&&(void 0!==a.offsetX?(d.clk_x=a.offsetX,d.clk_y=a.offsetY):"function"==typeof b.fn.offset?(c=c.offset(),d.clk_x=a.pageX-c.left,d.clk_y=a.pageY-c.top):(d.clk_x=a.pageX-f.offsetLeft,d.clk_y=a.pageY-f.offsetTop));setTimeout(function(){d.clk=
d.clk_x=d.clk_y=null},100)}function s(){if(b.fn.ajaxSubmit.debug){var a="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(a):window.opera&&window.opera.postError&&window.opera.postError(a)}}var z,B;z=void 0!==b("<input type='file'/>").get(0).files;B=void 0!==window.FormData;var D=!!b.fn.prop;b.fn.attr2=function(){if(!D)return this.attr.apply(this,arguments);var a=this.prop.apply(this,arguments);return a&&a.jquery||"string"===typeof a?a:
this.attr.apply(this,arguments)};b.fn.ajaxSubmit=function(a){function f(a){a=b.param(a).split("&");var d=a.length,f=[],g,c;for(g=0;g<d;g++)a[g]=a[g].replace(/\+/g," "),c=a[g].split("="),f.push([decodeURIComponent(c[0]),decodeURIComponent(c[1])]);return f}function c(d){for(var g=new FormData,c=0;c<d.length;c++)g.append(d[c].name,d[c].value);if(a.extraData)for(d=f(a.extraData),c=0;c<d.length;c++)d[c]&&g.append(d[c][0],d[c][1]);a.data=null;c=b.extend(!0,{},b.ajaxSettings,a,{contentType:!1,processData:!1,
cache:!1,type:m||"POST"});a.uploadProgress&&(c.xhr=function(){var b=jQuery.ajaxSettings.xhr();b.upload&&b.upload.addEventListener("progress",function(b){var c=0,d=b.loaded||b.position,g=b.total;b.lengthComputable&&(c=Math.ceil(d/g*100));a.uploadProgress(b,d,g,c)},!1);return b});c.data=null;var h=c.beforeSend;c.beforeSend=function(a,b){b.data=g;h&&h.call(this,a,b)};return b.ajax(c)}function d(c){function d(){function a(){try{var b=(r.contentWindow?r.contentWindow.document:r.contentDocument?r.contentDocument:
r.document).readyState;s("state = "+b);b&&"uninitialized"==b.toLowerCase()&&setTimeout(a,50)}catch(c){s("Server abort: ",c," (",c.name,")"),g(2),u&&clearTimeout(u),u=void 0}}var c=p.attr2("target"),k=p.attr2("action");f.setAttribute("target",q);m||f.setAttribute("method","POST");k!=e.url&&f.setAttribute("action",e.url);e.skipEncodingOverride||m&&!/post/i.test(m)||p.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});e.timeout&&(u=setTimeout(function(){v=!0;g(1)},e.timeout));var h=
[];try{if(e.extraData)for(var l in e.extraData)e.extraData.hasOwnProperty(l)&&(b.isPlainObject(e.extraData[l])&&e.extraData[l].hasOwnProperty("name")&&e.extraData[l].hasOwnProperty("value")?h.push(b('<input type="hidden" name="'+e.extraData[l].name+'">').val(e.extraData[l].value).appendTo(f)[0]):h.push(b('<input type="hidden" name="'+l+'">').val(e.extraData[l]).appendTo(f)[0]));e.iframeTarget||(w.appendTo("body"),r.attachEvent?r.attachEvent("onload",g):r.addEventListener("load",g,!1));setTimeout(a,
15);try{f.submit()}catch(n){document.createElement("form").submit.apply(f)}}finally{f.setAttribute("action",k),c?f.setAttribute("target",c):p.removeAttr("target"),b(h).remove()}}function g(a){if(!k.aborted&&!z){try{t=r.contentWindow?r.contentWindow.document:r.contentDocument?r.contentDocument:r.document}catch(c){s("cannot access response document: ",c),a=2}if(1===a&&k)k.abort("timeout"),x.reject(k,"timeout");else if(2==a&&k)k.abort("server abort"),x.reject(k,"error","server abort");else if(t&&t.location.href!=
e.iframeSrc||v){r.detachEvent?r.detachEvent("onload",g):r.removeEventListener("load",g,!1);a="success";var d;try{if(v)throw"timeout";var f="xml"==e.dataType||t.XMLDocument||b.isXMLDoc(t);s("isXml="+f);if(!f&&window.opera&&(null===t.body||!t.body.innerHTML)&&--A){s("requeing onLoad callback, DOM not available");setTimeout(g,250);return}var h=t.body?t.body:t.documentElement;k.responseText=h?h.innerHTML:null;k.responseXML=t.XMLDocument?t.XMLDocument:t;f&&(e.dataType="xml");k.getResponseHeader=function(a){return{"content-type":e.dataType}[a]};
h&&(k.status=Number(h.getAttribute("status"))||k.status,k.statusText=h.getAttribute("statusText")||k.statusText);var m=(e.dataType||"").toLowerCase(),p=/(json|script|text)/.test(m);if(p||e.textarea){var n=t.getElementsByTagName("textarea")[0];if(n)k.responseText=n.value,k.status=Number(n.getAttribute("status"))||k.status,k.statusText=n.getAttribute("statusText")||k.statusText;else if(p){var q=t.getElementsByTagName("pre")[0],C=t.getElementsByTagName("body")[0];q?k.responseText=q.textContent?q.textContent:
q.innerText:C&&(k.responseText=C.textContent?C.textContent:C.innerText)}}else"xml"==m&&!k.responseXML&&k.responseText&&(k.responseXML=B(k.responseText));try{y=G(k,m,e)}catch(F){a="parsererror",k.error=d=F||a}}catch(E){s("error caught: ",E),a="error",k.error=d=E||a}k.aborted&&(s("upload aborted"),a=null);k.status&&(a=200<=k.status&&300>k.status||304===k.status?"success":"error");"success"===a?(e.success&&e.success.call(e.context,y,"success",k),x.resolve(k.responseText,"success",k),l&&b.event.trigger("ajaxSuccess",
[k,e])):a&&(void 0===d&&(d=k.statusText),e.error&&e.error.call(e.context,k,a,d),x.reject(k,"error",d),l&&b.event.trigger("ajaxError",[k,e,d]));l&&b.event.trigger("ajaxComplete",[k,e]);l&&!--b.active&&b.event.trigger("ajaxStop");e.complete&&e.complete.call(e.context,k,a);z=!0;e.timeout&&clearTimeout(u);setTimeout(function(){e.iframeTarget||w.remove();k.responseXML=null},100)}}}var f=p[0],h,e,l,q,w,r,k,v,u,x=b.Deferred();if(c)for(h=0;h<n.length;h++)c=b(n[h]),D?c.prop("disabled",!1):c.removeAttr("disabled");
e=b.extend(!0,{},b.ajaxSettings,a);e.context=e.context||e;q="jqFormIO"+(new Date).getTime();e.iframeTarget?(w=b(e.iframeTarget),(h=w.attr2("name"))?q=h:w.attr2("name",q)):(w=b('<iframe name="'+q+'" src="'+e.iframeSrc+'" />'),w.css({position:"absolute",top:"-1000px",left:"-1000px"}));r=w[0];k={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(a){var c="timeout"===a?"timeout":
"aborted";s("aborting upload... "+c);this.aborted=1;try{r.contentWindow.document.execCommand&&r.contentWindow.document.execCommand("Stop")}catch(d){}w.attr("src",e.iframeSrc);k.error=c;e.error&&e.error.call(e.context,k,c,a);l&&b.event.trigger("ajaxError",[k,e,c]);e.complete&&e.complete.call(e.context,k,c)}};(l=e.global)&&0===b.active++&&b.event.trigger("ajaxStart");l&&b.event.trigger("ajaxSend",[k,e]);if(e.beforeSend&&!1===e.beforeSend.call(e.context,k,e))return e.global&&b.active--,x.reject(),x;
if(k.aborted)return x.reject(),x;(c=f.clk)&&(h=c.name)&&!c.disabled&&(e.extraData=e.extraData||{},e.extraData[h]=c.value,"image"==c.type&&(e.extraData[h+".x"]=f.clk_x,e.extraData[h+".y"]=f.clk_y));c=b("meta[name=csrf-token]").attr("content");(h=b("meta[name=csrf-param]").attr("content"))&&c&&(e.extraData=e.extraData||{},e.extraData[h]=c);e.forceSync?d():setTimeout(d,10);var y,t,A=50,z,B=b.parseXML||function(a,b){window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):
b=(new DOMParser).parseFromString(a,"text/xml");return b&&b.documentElement&&"parsererror"!=b.documentElement.nodeName?b:null},H=b.parseJSON||function(a){return window.eval("("+a+")")},G=function(a,c,d){var e=a.getResponseHeader("content-type")||"",f="xml"===c||!c&&0<=e.indexOf("xml");a=f?a.responseXML:a.responseText;f&&"parsererror"===a.documentElement.nodeName&&b.error&&b.error("parsererror");d&&d.dataFilter&&(a=d.dataFilter(a,c));"string"===typeof a&&("json"===c||!c&&0<=e.indexOf("json")?a=H(a):
("script"===c||!c&&0<=e.indexOf("javascript"))&&b.globalEval(a));return a};return x}if(!this.length)return s("ajaxSubmit: skipping submit process - no element selected"),this;var m,g,p=this;"function"==typeof a&&(a={success:a});m=this.attr2("method");g=this.attr2("action");(g=(g="string"===typeof g?b.trim(g):"")||window.location.href||"")&&(g=(g.match(/^([^#]+)/)||[])[1]);a=b.extend(!0,{url:g,success:b.ajaxSettings.success,type:m||"GET",iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":
"about:blank"},a);g={};this.trigger("form-pre-serialize",[this,a,g]);if(g.veto)return s("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return s("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var l=a.traditional;void 0===l&&(l=b.ajaxSettings.traditional);var n=[],h,q=this.formToArray(a.semantic,n);a.data&&(a.extraData=a.data,h=b.param(a.data,l));if(a.beforeSubmit&&!1===a.beforeSubmit(q,this,a))return s("ajaxSubmit: submit aborted via beforeSubmit callback"),
this;this.trigger("form-submit-validate",[q,this,a,g]);if(g.veto)return s("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;g=b.param(q,l);h&&(g=g?g+"&"+h:h);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+g,a.data=null):a.data=g;var v=[];a.resetForm&&v.push(function(){p.resetForm()});a.clearForm&&v.push(function(){p.clearForm(a.includeHidden)});if(!a.dataType&&a.target){var u=a.success||function(){};v.push(function(c){var d=a.replaceTarget?"replaceWith":"html";
b(a.target)[d](c).each(u,arguments)})}else a.success&&v.push(a.success);a.success=function(b,c,d){for(var f=a.context||this,g=0,e=v.length;g<e;g++)v[g].apply(f,[b,c,d||p,p])};h=0<b('input[type=file]:enabled[value!=""]',this).length;g="multipart/form-data"==p.attr("enctype")||"multipart/form-data"==p.attr("encoding");l=z&&B;s("fileAPI :"+l);var y;!1!==a.iframe&&(a.iframe||(h||g)&&!l)?a.closeKeepAlive?b.get(a.closeKeepAlive,function(){y=d(q)}):y=d(q):y=(h||g)&&l?c(q):b.ajax(a);p.removeData("jqxhr").data("jqxhr",
y);for(h=0;h<n.length;h++)n[h]=null;this.trigger("form-submit-notify",[this,a]);return this};b.fn.ajaxForm=function(a){a=a||{};a.delegation=a.delegation&&b.isFunction(b.fn.on);if(!a.delegation&&0===this.length){var f=this.selector,c=this.context;if(!b.isReady&&f)return s("DOM not ready, queuing ajaxForm"),b(function(){b(f,c).ajaxForm(a)}),this;s("terminating; zero elements found by selector"+(b.isReady?"":" (DOM not ready)"));return this}return a.delegation?(b(document).off("submit.form-plugin",this.selector,
u).off("click.form-plugin",this.selector,A).on("submit.form-plugin",this.selector,a,u).on("click.form-plugin",this.selector,a,A),this):this.ajaxFormUnbind().bind("submit.form-plugin",a,u).bind("click.form-plugin",a,A)};b.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};b.fn.formToArray=function(a,f){var c=[];if(0===this.length)return c;var d=this[0],m=a?d.getElementsByTagName("*"):d.elements;if(!m)return c;var g,p,l,n,h,q;g=0;for(q=m.length;g<q;g++)if(h=m[g],
(l=h.name)&&!h.disabled)if(a&&d.clk&&"image"==h.type)d.clk==h&&(c.push({name:l,value:b(h).val(),type:h.type}),c.push({name:l+".x",value:d.clk_x},{name:l+".y",value:d.clk_y}));else if((n=b.fieldValue(h,!0))&&n.constructor==Array)for(f&&f.push(h),p=0,h=n.length;p<h;p++)c.push({name:l,value:n[p]});else if(z&&"file"==h.type)if(f&&f.push(h),n=h.files,n.length)for(p=0;p<n.length;p++)c.push({name:l,value:n[p],type:h.type});else c.push({name:l,value:"",type:h.type});else null!==n&&"undefined"!=typeof n&&
(f&&f.push(h),c.push({name:l,value:n,type:h.type,required:h.required}));!a&&d.clk&&(m=b(d.clk),g=m[0],(l=g.name)&&!g.disabled&&"image"==g.type&&(c.push({name:l,value:m.val()}),c.push({name:l+".x",value:d.clk_x},{name:l+".y",value:d.clk_y})));return c};b.fn.formSerialize=function(a){return b.param(this.formToArray(a))};b.fn.fieldSerialize=function(a){var f=[];this.each(function(){var c=this.name;if(c){var d=b.fieldValue(this,a);if(d&&d.constructor==Array)for(var m=0,g=d.length;m<g;m++)f.push({name:c,
value:d[m]});else null!==d&&"undefined"!=typeof d&&f.push({name:this.name,value:d})}});return b.param(f)};b.fn.fieldValue=function(a){for(var f=[],c=0,d=this.length;c<d;c++){var m=b.fieldValue(this[c],a);null===m||"undefined"==typeof m||m.constructor==Array&&!m.length||(m.constructor==Array?b.merge(f,m):f.push(m))}return f};b.fieldValue=function(a,f){var c=a.name,d=a.type,m=a.tagName.toLowerCase();void 0===f&&(f=!0);if(f&&(!c||a.disabled||"reset"==d||"button"==d||("checkbox"==d||"radio"==d)&&!a.checked||
("submit"==d||"image"==d)&&a.form&&a.form.clk!=a||"select"==m&&-1==a.selectedIndex))return null;if("select"==m){var g=a.selectedIndex;if(0>g)return null;for(var c=[],m=a.options,p=(d="select-one"==d)?g+1:m.length,g=d?g:0;g<p;g++){var l=m[g];if(l.selected){var n=l.value;n||(n=l.attributes&&l.attributes.value&&!l.attributes.value.specified?l.text:l.value);if(d)return n;c.push(n)}}return c}return b(a).val()};b.fn.clearForm=function(a){return this.each(function(){b("input,select,textarea",this).clearFields(a)})};
b.fn.clearFields=b.fn.clearInputs=function(a){var f=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var c=this.type,d=this.tagName.toLowerCase();f.test(c)||"textarea"==d?this.value="":"checkbox"==c||"radio"==c?this.checked=!1:"select"==d?this.selectedIndex=-1:"file"==c?/MSIE/.test(navigator.userAgent)?b(this).replaceWith(b(this).clone(!0)):b(this).val(""):a&&(!0===a&&/hidden/.test(c)||"string"==typeof a&&b(this).is(a))&&(this.value=
"")})};b.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};b.fn.enable=function(a){void 0===a&&(a=!0);return this.each(function(){this.disabled=!a})};b.fn.selected=function(a){void 0===a&&(a=!0);return this.each(function(){var f=this.type;"checkbox"==f||"radio"==f?this.checked=a:"option"==this.tagName.toLowerCase()&&(f=b(this).parent("select"),a&&f[0]&&"select-one"==f[0].type&&f.find("option").selected(!1),
this.selected=a)})};b.fn.ajaxSubmit.debug=!0})(jQuery);
